language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install -g bower polymer-cli@next
  - npm install -g bower polylint web-component-tester
  - bower install
before_script:
  - polylint

script:
  - xvfb-run -s '-screen 0 1024x768x24' wct